### ISSUE TITLE
Translation error - tutorial

### ISSUE THREAD

**Issue by jonathan-chin** [bilingualgeneration/bili-app#117]
This translation feels off. "Incluido" should read "incluyendo" and the last part should read "sus actividades favoritas de Bili."

Also, are we translating the button text? They are still in English.

**Comment by fernperezg97** [comment]
@jonathan-chin I'm assuming that this is for the walkthrough in /settings/overview, is that correct? 🤔

**Comment by fernperezg97** [comment]
> @jonathan-chin I'm assuming that this is for the walkthrough (Joyride) in /settings/overview, is that correct? 🤔

Nevermind! Found and fixed the issues!

**Comment by fernperezg97** [comment]
Fixed in this PR: fer-translation-error-tutorial-fix
