### ISSUE TITLE
Translation error: Log out button not translating to Esp

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#120]
<img width="281" alt="Bili issue_2" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/771f6445-9950-4624-a592-2314dd83f1a4">

**Comment by fernperezg97** [comment]
Fixed in `commit d643789b9409c89c4d1d715f495fc28e8220e20e` in branch `fer-github-issues-fixes`

**Comment by fernperezg97** [comment]
Fixed in https://github.com/bilingualgeneration/bili-app/pull/127
