### ISSUE TITLE
Translation error: "About" section title

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#121]
I think this should read "Sobre Bili" or something like that, since "Acerca de" doesn't give the user enough information about what they'll be clicking on. Maybe we should also change "About" to say "About Bili"? But I think in English the implication [that upon clicking, you'll learn more about the app] is stronger.

<img width="280" alt="Bili issue_3" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/8b10959d-b323-4863-8320-aa37b5f909ea">

**Comment by fernperezg97** [comment]
Fixed in `commit d643789b9409c89c4d1d715f495fc28e8220e20e` in branch `fer-github-issues-fixes`

**Comment by fernperezg97** [comment]
Fixed in https://github.com/bilingualgeneration/bili-app/pull/127
