### ISSUE TITLE
Translation(?) error: Hello instead of Welcome

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#122]
This is already updated in the Figma file, so it may not be a translation error. This should say Hola, not Bienvenido. We want to avoid gendered words here. 

<img width="725" alt="Bili issue_4" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/45cfc4d6-f41a-415d-a668-2725af9d0bcd">

**Comment by fernperezg97** [comment]
Will be fixed once branch `fer-github-issue-fixes` is merged:

- Fixed in `commit c4c68b8753e44207d72a49b51ff8e9e7f21264dc` in `fer-github-issue-fixes` branch

**Comment by fernperezg97** [comment]
Fixed in https://github.com/bilingualgeneration/bili-app/pull/127
