### ISSUE TITLE
Audio error: Story Factory (🐰)

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#123]
Tested this a few different times and each time, the audio for 'el conejo' does not play. Can you check and see if this is the case and if so, update? Thank you! 

<img width="396" alt="Bili issue_11" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/d8837c2a-213c-488f-8f27-b1aeaaf8e061">

**Comment by jonathan-chin** [comment]
I forgot to include `el conejo` in our audio generation! it's been fixed
