### ISSUE TITLE
Translation error: Preferences 

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#124]
"Preferences" is not being translated [to Spanish] in Spanish language configuration mode

<img width="1020" alt="Bili issue_14" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/2949e00c-a0d1-4ea0-b2a2-e978337c3019">

**Comment by jonathan-chin** [comment]
@fernperezg97 check if the `.tsx` file uses the `FormattedMessage` component here. if it doesn't, add it and see if that fixes it. if it already does, let me know.

**Comment by fernperezg97** [comment]
@jonathan-chin it will be fixed once branch fer-github-issue-fixes is merged!

- Fixed in `commit 37570095439c5e2344b5bc32d0d27fd1c284e6fb` in `fer-github-issue-fixes` branch

**Comment by fernperezg97** [comment]
Fixed in https://github.com/bilingualgeneration/bili-app/pull/127
