### ISSUE TITLE
Formatting error: Daily limit drop-down

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#125]
There should be a space between 30 and "min"! 

<img width="236" alt="Bili issue_13" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/fa94a946-a530-4281-9579-11746295e22a">

**Comment by jonathan-chin** [comment]
I believe this is on the `Settings` page, maybe in Preferences?

**Comment by fernperezg97** [comment]
Will be fixed once branch `fer-github-issue-fixes` is merged:

- Fixed in `commit 28dd622379ff37524733626f927c5e4bc8bf99e5` in `fer-github-issue-fixes` branch

**Comment by fernperezg97** [comment]
Fixed in https://github.com/bilingualgeneration/bili-app/pull/127
