### ISSUE TITLE
Translation error: Story factory

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#126]
Should read "los sábados" (with accent)

<img width="352" alt="Bili issue_8" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/d5a0b6a2-93f0-4089-8e45-472900ee465c">

**Comment by jonathan-chin** [comment]
we'll have to regenerate the audio file for that. I'll take care of it.

**Comment by jonathan-chin** [comment]
fixed!
