### ISSUE TITLE
Onboarding - Mode Selection Error

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#133]
Should say "Modo Español"
<img width="183" alt="Screenshot 2024-01-23 at 1 05 20 PM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/8d7e619c-ded8-4be4-bf5a-3565b4db0e94">

**Comment by amak-code** [comment]
@jonathan-chin maybe it was not translated properly by locaze? I fixed it in es.json, though I understood it's not needed. 
.tsx has a proper English default text.

**Comment by jonathan-chin** [comment]
@amak-code this change should be made in locize

**Comment by amak-code** [comment]
Fixed in locize.
<img width="442" alt="Screen Shot 2024-01-24 at 4 58 43 PM" src="https://github.com/bilingualgeneration/bili-app/assets/70419097/17d8f6e1-8014-4828-9171-844bb43f33b5">
