### ISSUE TITLE
Onboarding ENG Text - Sentence Case vs. Title Case

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#136]
The "I" in "immersion" (of "Spanish Immersion") should be capitalized (title case)
<img width="256" alt="Screenshot 2024-01-23 at 9 50 13 AM copy" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/5e640d1b-92a6-47b2-aef9-6ea9705a4c02">

**Comment by jonathan-chin** [comment]
@fernperezg97 can you fix this in locize? you can close this issue once its done

**Comment by fernperezg97** [comment]
Fixed in `commit 1d8470658af9cd68daad86a2a31c72b66a68c023` in `fer-assigned-github-issues`
