### ISSUE TITLE
Onboarding - required element, google/apple email capacity missing

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#137]
-Your full name should be required field (missing in teacher onboarding only)
-Should allow google and apple emails (both language versions)
<img width="398" alt="Screenshot 2024-01-23 at 9 53 25 AM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/ca04e059-1af9-40c1-ab82-929ae0bf985f">

**Comment by jonathan-chin** [comment]
> Your full name should be required field (missing in teacher onboarding only)

good catch! @amak-code can you fix this? you should just need to pass the `required={true}` prop in the correct place.

> Should allow google and apple emails (both language versions)

this is SSO sign up, using your Google and/or Apple account. it requires a good chunk of dev time and it's pretty low on our priority list. maybe we can remove it from the MVP for now?

**Comment by jonathan-chin** [comment]
this is in `/pages/SignUp/TeacherAccountCredentials.tsx`

for the SSO options and the or divider, you should be able to just add `ion-hide` to the classes

**Comment by amak-code** [comment]
Fixed in commit: [Teacher sign up form was fixed](https://github.com/bilingualgeneration/bili-app/commit/4cdc334e951c78c03a287d328d422ebedb28bf65)
