### ISSUE TITLE
implement translation solution

### ISSUE THREAD

**Issue by jonathan-chin** [bilingualgeneration/bili-app#14]
search for keywords like react i18n

**Comment by fernperezg97** [comment]
# Given that our tech stack includes Ionic with React/TypeScript, Strapi, AWS, and Firebase, here's what I've considered while evaluating the best i18n solution for our project @jonathan-chin @amak-code:

**1. Support for Multiple Languages:**
We are planning to support many languages, so it's crucial that the i18n library we choose can efficiently handle multiple languages and dynamic language switching. 

**2. Ease of Use:**
It's essential that the library is user-friendly and can be easily integrated into our existing tech stack. Given that we're using React, libraries with strong React integration are preferable for us.

**3. Translation Management:**
As we grow and introduce more languages, managing translations becomes a challenge. Therefore, we should look for a library that offers tools or workflows for managing translations effectively.

**4. Pluralization and Gender Support:**
Some languages have complex grammar rules, so we should consider libraries that provide support for pluralization and gender-specific translations.

**5. Performance:**
The library's performance is critical, especially when we're dealing with a large number of translations or dynamically loading translations. This can significantly impact the user experience.

**6. Community and Documentation:**
We need to ensure that the library has strong community support and comprehensive documentation. An active community can be a valuable resource for assistance and issue resolution.

**7. Integration with Ionic and React:**
   Compatibility with our tech stack is vital. The selected i18n solution should seamlessly integrate with our Ionic and React application without causing conflicts or compatibility issues.

**8. Scalability:**
As we plan to introduce numerous languages, scalability is a key consideration. The chosen i18n library should efficiently handle a growing number of translations.

### Based on these criteria, two strong options for our project are:

**1. react-intl:**
React-intl is a robust and widely used internationalization library that offers comprehensive support for multiple languages, dynamic language switching, and robust formatting options. It aligns well with our tech stack and is tailored for React and TypeScript.

   - **Pros:**
     - Excellent support for multiple languages.
     - Strong React integration.
     - Rich formatting capabilities.
     - Active community and extensive documentation.
     - Pluralization and gender support.

   - **Cons:**
     - May be considered complex for very basic use cases.

   GitHub Repository: [react-intl](https://github.com/formatjs/react-intl)

**2. i18next:**
 i18next is a versatile i18n library known for its good support for multiple languages and dynamic language switching. It offers high configurability and can be effectively used with React.

   - **Pros:**
     - Strong support for multiple languages.
     - Highly configurable and versatile.
     - Works well with React.
     - Suitable for managing translations.

   - **Cons:**
     - Configuration may be more involved.

   GitHub Repository: [i18next](https://github.com/i18next/i18next)

So, I'd say that these are our top contenders. We should chat about which one feels more comfy for us and suits our project's needs best. I can do some more research if you guys think we need more insight or we can talk about it this Friday and decide together which way to go!

**Thanks, y'all!**

**Comment by jonathan-chin** [comment]
I reviewed both more in depth. initially, i18next seemed better but both seem to be on par in terms of feature sets, plugins, and community support.

react-intl seems to have more support, based on GitHub stars. so I think we'll be going with that.

**Comment by jonathan-chin** [comment]
@fernperezg97 need to update all components in `SignUp` to use `react-intl`
