### ISSUE TITLE
Onboarding - Translation missing (ESP) (choose your plan)

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#140]
"Best value" has not been translated. Should be "mejor valor"

<img width="486" alt="Screenshot 2024-01-23 at 1 43 14 PM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/15fb0ee3-b17a-4257-94b1-64dd1cdcc0a2">

**Comment by jonathan-chin** [comment]
@amak-code not sure if you fixed this in your current sprint. if not, @fernperezg97 can you fix it?

**Comment by fernperezg97** [comment]
Fixed in `commit 8faf90bf897856f5f842e514cd89eafcb67d995f` in `fer-assigned-github-issues`
