### ISSUE TITLE
Home page issues immediately after signup

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#141]
1. After signing up in English mode, the tutorial invitation on the home page shows up only in Spanish. It should be in English for English mode and Spanish for Spanish mode. 
2. The tutorial should help direct user to settings section. Right now it shows up in the middle of the screen with no indication of where the user should go next.
3. The button in the tutorial dialog box says "Cerrar" (Close). Do we need this button if there is also an X? This button should either direct people to settings ("Go to settings") or be an "Okay" button. 
4. When you hover over the "Cerrar" button the hover effect says "Last." Can we remove this?
5. The tutorial invites user to "Click here" ("Haga clic aquí") but it's not clear where "here" is. The only button is "Cerrar." There should be more direction and clarity here or we should rephrase the tutorial language altogether. It should say something like: "Welcome to Bili! Before you start exploring, visit the settings page to personalize your child/ren's learning experience" and either direct the user to click on the User icon or include a button that says "Personalize Bili" or "Complete app setup" etc.
<img width="419" alt="Screenshot 2024-01-23 at 9 59 04 AM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/1ed8cd87-2ce8-4259-889d-6a2364dd3055">

**Comment by jonathan-chin** [comment]
> The tutorial should help direct user to settings section. Right now it shows up in the middle of the screen with no indication of where the user should go next.

this is a technical issue. there's a race condition that does not allow us to highlight specifically the settings button. I can try and debug it further but can't guarantee there's a fix.
