### ISSUE TITLE
Language mode errors - settings 

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#142]
After signing up in english mode:
1. Settings menu is in Spanish
2. Math problem prompt is in Spanish
3. Configuration language is automatically set to Spanish

Can we clean this up so that users don't have to reset their configuration language?

**Comment by jonathan-chin** [comment]
I think we need to retool language to have both a 'game' language and a 'settings' language. currently, we only have a single language and automatically set it to Spanish on sign up so the rest of the app works.

**Comment by jonathan-chin** [comment]
should be fixed in latest update.
