### ISSUE TITLE
Math problem - adult check

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#144]
1. These math problems take too long. Can we make them single-digit additions?
2. Can we add additional context to this screen? "This section is for grown-ups only! Please confirm that you are an adult." 
3. Can we make it so that if you hit enter on the keyboard to submit the answer, it automatically continues? Right now you can only go on if you click Continue with the mouse. 

<img width="872" alt="Screenshot 2024-01-23 at 10 04 03 AM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/62662520-c168-4cc8-88bd-ffe1af8a7679">

**Comment by jonathan-chin** [comment]
> These math problems take too long. Can we make them single-digit additions?

will have to run by vero. for rapid testing, you can submit the word debug and skip it.

> Can we add additional context to this screen? "This section is for grown-ups only! Please confirm that you are an adult."

yes, we just need the text and wording

> Can we make it so that if you hit enter on the keyboard to submit the answer, it automatically continues? Right now you can only go on if you click Continue with the mouse.

there was an issue with that during dev. I can't remember exactly why but I went out of my way to disable the enter key. I can look at it again.
