### ISSUE TITLE
Settings - Issues making profile changes

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#148]
After we changed to English mode, we tried to change the user Full name and when we clicked save, it also changed the configuration language to Spanish. Tested 3x with same result. It doesn't happen if you make the change in Spanish configuration mode.

**Comment by jonathan-chin** [comment]
interesting. noted.

**Comment by jonathan-chin** [comment]
@amak-code I think I fixed this in the latest update. can you double check if this is still an issue? if it is fixed, feel free to close this.
