### ISSUE TITLE
Settings - Preferences more info

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#149]
1. Can we make the more info "?" hoverable for browser/cursor users?
2. Bilingual vs. Immersion Mode dialog box: Add apostrophe for Bilingual and Immersion like in the other dialog boxes: "Choose the language mode for your child's experience in the app. 'Bilingual' means your child will see the content in English and Spanish. 'Immersion' means your child will only see the content in Spanish."
<img width="545" alt="Screenshot 2024-01-23 at 3 13 36 PM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/547ca50e-5459-40d4-95f0-34f8040110a8">

**Comment by jonathan-chin** [comment]
@fernperezg97 can you update the english and spanish on this in locize? close the issue when you've done it.

**Comment by fernperezg97** [comment]
Fixed both of these issues in `commit 5f8c75362ab4a2466fda464969916e9f877df872` in `fer-assigned-github-issues`
