### ISSUE TITLE
El Intruso - Intro page language mode errors

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#152]
Bilingual vs. immersion mode setting is not working:
1. Spanish configuration with immersion mode **works** - all in Spanish
2. Spanish config with bilingual mode **works** - shows up Bilingual
3. English config with immersion mode **doesn't work** - shows up English only
4. English config with bilingual mode **doesn't work** - shows up English with English subtitles (all english)
<img width="965" alt="Screenshot 2024-01-23 at 3 56 45 PM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/6b879e5b-a58a-4a93-965d-7a718bbb5179">
<img width="930" alt="Screenshot 2024-01-23 at 3 54 59 PM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/751380a2-8ba7-4522-863a-91014b9ef623">
<img width="957" alt="Screenshot 2024-01-23 at 3 51 27 PM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/d09d9b21-9a13-4edd-adf0-ef09243261c0">

**Comment by jonathan-chin** [comment]
fixed the English issue in latest update.

@fernperezg97 can you double check the Spanish translation in Maried's last screenshot? I think it can be fixed in locize. if you can fix it in locize, feel free to close this issue.

**Comment by fernperezg97** [comment]
@jonathan-chin have the issues from the rest of the screenshots aside from the last one been fixed already?

**Comment by fernperezg97** [comment]
@jonathan-chin @mariedr I've fixed the text not displaying, BUT the bigger issue is that there is no English audio for this section, which I think is why Sasha must have done it this way in the beginning. The audio goes right to, "The goal of this game is to identify the word that does not rhyme with the rest," and bypasses the, "Welcome to "The Intruder" game!" introductory phrase.
