### ISSUE TITLE
General/Homepage - Bilingual vs. Immersion Mode Issue 

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#153]
Bilingual vs. immersion mode setting is not working:
1. Spanish configuration with immersion mode **works** - all in Spanish
2. Spanish config with bilingual mode **works** - shows up Bilingual
3. English config with immersion mode **doesn't work** - shows up English only
<img width="1355" alt="Eng config, immersion mode" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/83b4756e-79cb-4e44-8855-82c4debe2ecd">
4. English config with bilingual mode **doesn't work** - shows up English with English subtitles (all english)
<img width="1343" alt="Eng config, bilingual mode" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/2bf437fb-20b6-4643-8fd0-9e3bcb07cfc3">

**Comment by jonathan-chin** [comment]
so technically, the app should never be in English mode. the option is for English in the settings page. we can discuss tomorrow.

**Comment by jonathan-chin** [comment]
fixed in latest updates.
