### ISSUE TITLE
El intruso - font weight/size 

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#154]
prompt font wrong weight- should matc Figma file (bold) 
<img width="1160" alt="Screenshot 2024-01-23 at 3 49 12 PM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/a50ca235-3519-426a-9cde-577f1d6bedab">

**Comment by jonathan-chin** [comment]
we're syncing with Sarah to consolidate several font styles.
