### ISSUE TITLE
El intruso - change sound effect

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#155]
Replace card flip audio (new sound, shorter, sounds less like a fart) - see [drive file](https://drive.google.com/file/d/10kX21YLd-IfsWEOpdK1Nr4iFxmCLRtiM/view?ts=65afdfb5). Slack me if you can't access it

**Comment by amak-code** [comment]
@mariedr we discussed this sound in Slack. The sound that you provided is good, but short for our card motion. The card motion lasts 2 seconds and the sound lasts maybe one second. So it might be not a very good fit. Let me know your thoughts)
P.S. Did the users say that it sounded like fart? :)))

**Comment by jonathan-chin** [comment]
@Beck-bili including you in this conversation since Maried is OOO.

the sound effect has been updated and ready for review.
