### ISSUE TITLE
Settings - Change items to title case

### ISSUE THREAD

**Issue by mariedr** [bilingualgeneration/bili-app#156]
change preferences items to Title case 
<img width="1036" alt="Screenshot 2024-01-23 at 2 52 02 PM" src="https://github.com/bilingualgeneration/bili-app/assets/156923168/151f6edd-5fea-4641-bce1-772937c084c1">

**Comment by jonathan-chin** [comment]
@fernperezg97 I think you can fix this in locize. be sure to also change the Spanish. close this issue when fixed.

**Comment by fernperezg97** [comment]
- Just a quick note: In Spanish, the proper "grammatical" thing to do is to only capitalize the first word and then only any proper names! 😄
- I made the suggested updates in Locize and in Preferences.tsx in `commit 05c524176403236dbebe322880d3e656bcef8a67` in `fer-assigned-github-issues`
