### ISSUE TITLE
Translations on Settings Page - settings are showing up in English

### ISSUE THREAD

**Issue by Beck-bili** [bilingualgeneration/bili-app#162]
In Spanish mode, settings are showing up in English

<img width="1618" alt="Screenshot 2024-01-24 at 8 39 11 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/1bbbc513-51f0-4ea2-93ca-62b4af3acfc0">

**Comment by jonathan-chin** [comment]
@amak-code I think you are better suited to handle this, since I think you build this page. it's changed a little bit since you've last seen it, so please branch from the latest `main`
