### ISSUE TITLE
Story Factory - Intro page Audio question

### ISSUE THREAD

**Issue by Beck-bili** [bilingualgeneration/bili-app#164]
Is the audio going to play automatically every single time? There should be a skip button for the game intros. Can we have it show up after the first time you hear it? Or activate the button right away.

**Comment by jonathan-chin** [comment]
@Beck-bili yes, it is playing for every intro screen. an option is to skip the intros after the first time they're played.

if there should be a skip button, we'll need some designs on figma for that. it doesn't have to be hi fidelity.
