### ISSUE TITLE
Story Factory - Next Button Translation

### ISSUE THREAD

**Issue by Beck-bili** [bilingualgeneration/bili-app#165]
Translation: Proximo should be Siguiente
<img width="1601" alt="Screenshot 2024-01-24 at 8 46 52 AM" src="https://github.com/bilingualgeneration/bili-app/assets/157525984/0e42ab60-68f4-446d-83ed-cebdffe82690">

**Comment by jonathan-chin** [comment]
@Beck-bili I think this is fixed. feel free to reopen if I'm wrong.

in general, fixes appear every Monday morning and I think this was an older issue.

**Comment by Beck-bili** [comment]
Just checked and still see "Próximo"

**Comment by fernperezg97** [comment]
@jonathan-chin I can take care of it in Locize 👌

**Comment by fernperezg97** [comment]
Saved in Locize @jonathan-chin! Will be updated next round of updates @Beck-bili!
