### ISSUE TITLE
update correct and incorrect mp3 audio

### ISSUE THREAD

**Issue by jonathan-chin** [bilingualgeneration/bili-app#282]
we're now using the `intruder_correct.mp3` and `intruder_correct.mp3` in multiple places. let's streamline it

- [x] move mp3 files into `@/assets/audio` as just `correct.mp3` and `incorrect.mp3`
- [x] update all files that reference `intruder_correct.mp3` and `intruder_incorrect.mp3`

**Comment by amak-code** [comment]
This issue was resolved in `commit a65c29f56b2626c270c90d9d0f06b086dfb61ae7`.
