### ISSUE TITLE
CMS Audio Filename Convention

### ISSUE THREAD

**Issue by fernperezg97** [bilingualgeneration/bili-app#66]
1. Default to English 
    * start with 'sf' for story factory as opposed to 'fábrica' for all file names 
    * ex. sf_the_clouds
2. Different language code goes at the end of the file name, but actual filename name is the same for audio files in different languages
    * ex. cannot have the_clouds/las_nubes instead has to be the_cloud_en/the_cloud_es
3. Cannot have accented characters even if it is not the correct Spanish spelling
    * ex. cannot have doña_maría instead has to be dona_maria
4. Use underscores in place of spaces
    * ex. cannot have 'sf animals' instead has to be 'sf_animals'
5. No capital letters
    * ex. cannot have 'ms_Anna' instead has to be 'ms_anna'

**Comment by jonathan-chin** [comment]
created training video 2023-13-07
