### ISSUE TITLE
React Onboarding

### ISSUE THREAD

**Issue by jonathan-chin** [bilingualgeneration/bili-app#71]
We need to implement an Onboarding library for the Settings page. possible ones are:

1. r-onboarding - https://github.com/fatihsolhan/r-onboarding
2. react-joyride - https://github.com/gilbarbara/react-joyride
3. shepherd - https://github.com/shipshapecode/react-shepherd

note: MUST work with Ionic, which might have weird interactions with page scrolling.

**Comment by Akash5908** [comment]
@jonathan-chin I have a good knowledge in React and I want to work on this Issue, could you assign it to me please?

**Comment by jonathan-chin** [comment]
went with react-joyride
