### ISSUE TITLE
DOB Color

### ISSUE THREAD

**Issue by fernperezg97** [bilingualgeneration/bili-app#76]
### Specifically on Settings2 page
Currently, Ionic's date type is a little problematic in the sense that it's hard to change the 'placeholder' color.

**Comment by jonathan-chin** [comment]
fixed with this https://stackoverflow.com/questions/69752956/ion-input-of-type-date-has-calendar-icon-of-the-wrong-color

currently, just applying `filter: invert(1)` to `theme/overrides.scss` but might need to modify further

**Comment by jonathan-chin** [comment]
additionally coloring the placeholder in the same file
